### ISSUE TITLE
Add ip-whitelist for private GIT server 

### ISSUE THREAD

**Issue by ducngo-jmango360** [codenvy/docs#135]
Hi, I'm trying to evaluate codenvy.io hosted IDE as an alternative for our dev environment.
I need to whitelist our own gitlab server at gitlab.jmango360.com, please help.

Thanks,
Duc

**Comment by vkuznyetsov** [comment]
Hello @ducngo-jmango360 
Is this issue still actual for you?

**Comment by skryzhny** [comment]
Done.
