### ISSUE TITLE
Post-GA docs fixes

### ISSUE THREAD

**Issue by bmicklea** [codenvy/docs#2]
After we ship 5.0.0 we should clean up some things in the docs:
- [x] Brad:`docs.sh` should be in the root directory if possible
- [ ] Serhii: Add "Monitoring" section to managing.md
- [x] Eugene: Create guide to white labelling, especially how to add/remove plugins
- [x] Serhii: Update `runbook.md` with additional info

**Comment by JamesDrummond** [comment]
@bmicklea Can this issue be closed?

**Comment by bmicklea** [comment]
No, there are three items still not complete.

**Comment by bmicklea** [comment]
@skryzhny - can you please write up (in .md file) how to setup monitoring for Codenvy using the defaults you use in `codenvy.io`.

Fidelity needs to see it soon.

**Comment by eivantsov** [comment]
> Create guide to white labelling, especially how to add/remove plugins

Currently, we do not have any white labeling mechanism that is worth documenting. The old fashioned way - creating a custom assembly.
