### ISSUE TITLE
Add Documentation for Permissions API

### ISSUE THREAD

**Issue by slemeur** [codenvy/docs#41]
We have introduced Permissions API and this is having an impact to the end-user.

We need to document:
- all resources (workspace, factory?, account, organization) that are impacted by permissions
- for each of the resource, we need to list and describe all the permissions values (read, write...)
- if applicable, for each resource describe how to change those permissions.

**Comment by riuvshin** [comment]
@slemeur @TylerJewell do we need 5.2.0 milestone here? 5.2.0 release is in few days.

**Comment by TylerJewell** [comment]
The milestone should be applied by a team leader when there is a valid pr that they are confident will be merged. We don't have these items yet.

**Comment by riuvshin** [comment]
@TylerJewell exactly, that is why I've asked. those things are not ready but milestone is set.
@slemeur please drop the milestone

**Comment by slemeur** [comment]
Cross link with https://github.com/codenvy/codenvy/pull/1451

**Comment by slemeur** [comment]
Fixed here: https://github.com/codenvy/docs/pull/87
