### ISSUE TITLE
Team documentation

### ISSUE THREAD

**Issue by slemeur** [codenvy/docs#42]
Provide documentation about teams.

We need to describe:
- What are Teams, team's workspaces and team's resources?
- How to create a team?
- How to invite someone into a team and assign permissions? and how to increase seats
- How to create a team workspace?
- How to move a workspace into a team?
- What are team resources?
- How to administrate the caps and limits?

(this issue can be splitted and divided)

**Comment by riuvshin** [comment]
@slemeur @TylerJewell do we need 5.2.0 milestone here? 5.2.0 release is in few days.

**Comment by TylerJewell** [comment]
The milestone should be applied by a team leader when there is a valid pr that they are confident will be merged. We don't have these items yet.

**Comment by riuvshin** [comment]
@TylerJewell exactly, that is why I've asked. those things are not ready but milestone is set.
@slemeur please drop the milestone

**Comment by slemeur** [comment]
Fixed here: https://github.com/codenvy/docs/pull/87
