### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by wernight** [codenvy/docs#99]
Issues on https://codenvy.com/docs/getting-started/admin-intro/index.html:

  - Link "Improve this page" broken, as it points to https://github.com/codenvy/docs/blob/master/src/main/_docs/workspace-administration/ws-admin-intro.md
  - Markdown broken, shows `## 1. Create a workspace with a production runtime` in the HTML.

Issues on https://codenvy.com/docs/user-guide/import/index.html:

  - Bullet lists broken

**Comment by bmicklea** [comment]
@JamesDrummond - I fixed the heading on workspaces admin but the improve this page link is still wrong. It should point to the che-docs repo and the workspace-admin/intro page.

@JamesDrummond - I added a PR in che-docs to try and fix the bullets although looking at the .md I didn't see anything wrong with it so if it's still rendering wrong on the site it may be some kind of Jekyll issue...

**Comment by JamesDrummond** [comment]
PR created https://github.com/codenvy/docs/pull/107

**Comment by JamesDrummond** [comment]
@wernight Be sure to checkout the new factory I created to make editing docs much easier https://codenvy.io/f?name=che-codenvy-docs&user=jdrummond

**Comment by wernight** [comment]
Could you add a badge on GitHub README for that factory? I think that's how it's supposed to work (at least that's what I did on https://github.com/wernight/scruffy-server).

**Comment by slemeur** [comment]
@wernight 100% right. Added.

**Comment by bmicklea** [comment]
PR merged. Fixed
